/** Rotating status lines shown while an agent waits for the first streamed token. */
export const AGENT_LOADING_PHRASES: Record<string, string[]> = {
  build: [
    "Reading the brainstorm idea…",
    "Mapping system boundaries…",
    "Drafting architecture layers…",
    "Structuring execution phases…",
    "Choosing technology patterns…",
    "Defining module responsibilities…",
    "Sketching data flows…",
    "Aligning plan with constraints…",
    "Balancing scope and feasibility…",
    "Composing the build delta…",
    "Checking canonical state shape…",
    "Preparing structured JSON output…",
  ],
  review: [
    "Scanning architecture decisions…",
    "Looking for gaps and blind spots…",
    "Evaluating technical risks…",
    "Cross-checking assumptions…",
    "Reviewing execution dependencies…",
    "Stress-testing the plan…",
    "Identifying open questions…",
    "Comparing against best practices…",
    "Flagging severity and impact…",
    "Drafting review findings…",
    "Prioritising what matters most…",
    "Preparing the review delta…",
  ],
  refine: [
    "Reading prior agent output…",
    "Smoothing rough edges…",
    "Tightening phase definitions…",
    "Improving clarity and structure…",
    "Resolving ambiguous wording…",
    "Strengthening weak areas…",
    "Harmonising architecture and plan…",
    "Polishing deliverable scope…",
    "Refining metrics and confidence…",
    "Consolidating overlapping items…",
    "Preparing the refine delta…",
    "Almost ready to emit changes…",
  ],
  devils_advocate: [
    "Questioning core assumptions…",
    "Hunting for failure modes…",
    "Probing scalability limits…",
    "Challenging happy-path thinking…",
    "Looking for hidden dependencies…",
    "Stress-testing timelines…",
    "Surfacing worst-case scenarios…",
    "Checking for single points of failure…",
    "Debating trade-off choices…",
    "Finding what was left unsaid…",
    "Preparing skeptical counterpoints…",
    "Drafting the challenge delta…",
  ],
};

export const DEFAULT_LOADING_PHRASES: string[] = [
  "Connecting to the language model…",
  "Loading session context…",
  "Preparing the agent prompt…",
  "Waiting for the first token…",
  "Reasoning over canonical state…",
  "Structuring the response…",
  "Streaming will begin shortly…",
  "Still working — large models take a moment…",
  "Synthesising agent output…",
  "Composing JSON delta…",
  "Hang tight — output is on the way…",
  "Processing your brainstorm…",
];
